feat/achieve-alarm
WakGames/Waktaverse-Games-Demo-Unity pull request #3
Opened 2024-07-07 04:11 UTC by turtle85917

- 업적 클리어 시, 알람창이 띄어짐
- 스탯을 통해 클리어 시, 알람창이 한 번에 나옴

https://github.com/WakGames/Waktaverse-Games-Demo-Unity/assets/61219276/dca45707-c919-49e0-b5b7-acf73ebcd468

2024-07-07 04:13 UTC, turtle85917 commented
@DOS0313 @NeuroWhAI

2024-07-08 02:14 UTC, DOS0313 commented
도전과제 알림이 올라오는 모션이 너무 딱딱하고 빠른 것 같은데 조정 가능하실까요?
(말로 설명이 어려워서 시간 되시면 저녁에 통화방에서 한번 미팅 가지시는 것도?)

2024-07-08 07:13 UTC, turtle85917 commented
그렇게 하죠

2024-07-09 04:52 UTC, NeuroWhAI requested changes
고생 많으셨습니다. 요것들 한번 검토 부탁드립니다.

2024-07-09 04:52 UTC, NeuroWhAI commented on Assets/Scripts/MenuBehaviour.cs
> +    }
이 테스트 버튼 및 기능은 삭제 부탁드립니다.
데모 코드는 다른 분들이 참조하시기 편하게 꼭 필수적인 것만 포함하려고 하고 있습니당.

임의로 알림을 띄우는 걸 지원하겠다면 이것도 있으면 좋을 것 같긴 한데 그러려면 API 응답 객체를 받는 NewAlarm(s) 메서드는 내부용으로 두고 별도 전용 개체를 받는 SDK API를 따로 만들어두는 게 나을 것 같네요.
그리고 이 기능을 남겨두실 것이라면 ㄴㅇㄱ 문구는 바꿔주세용.

2024-07-09 04:52 UTC, NeuroWhAI commented on Assets/Scripts/AchievePanel.cs
> +    public void Setup(AchievementsResultItem achievement, Texture2D texture, int index = -1)
요거 `AchievementsResultItem` 자료형을 사용하는 것 보단 name, desc로 파라미터 분리하는 게 쓰는 쪽에서 더 나을 것 같습니다.

2024-07-09 04:52 UTC, NeuroWhAI commented on Assets/Scripts/AchievePanel.cs
> +        m_wakgamesAchieve = FindObjectOfType<WakgamesAchieve>();
코드상 다른 곳도 포함해서 `FindObjectOfType<WakgamesAchieve>()` 사용시 `null`이 반환될 수 있는 가능성을 고려해야할 것 같습니다.
아무래도 사용법을 다들 잘 알고 쓰시진 않을테니 `null`이 반환되면 안 되는 곳에서는 해결책과 함께 알기 쉬운 오류를 띄워준다던가 반환되어도 크게 문제가 없는 곳에서는 `null` 참조 오류가 발생하지 않도록 방어하면 될 거 같습니다.

2024-07-09 04:52 UTC, NeuroWhAI commented on Assets/Scripts/MenuBehaviour.cs
> +    private RawImage[] RawImage;
이건 혹시 용도가 어떻게 될까요?
이미 달성된 도전과제 불러오는 `AppendAchievementMessage` 부분에서 이미지 로딩해서 여기 넣던데...

2024-07-10 06:58 UTC, turtle85917 commented on Assets/Scripts/MenuBehaviour.cs
> +    }
확인했습니다. 코드 지우겠습니다. 임의로 알림 띄우는건 지원할 필요가 없어보이네요

2024-07-10 06:58 UTC, turtle85917 commented on Assets/Scripts/AchievePanel.cs
> +    public void Setup(AchievementsResultItem achievement, Texture2D texture, int index = -1)
확인했습니다. 코드 수정하겠습니다.

2024-07-10 07:00 UTC, turtle85917 commented on Assets/Scripts/AchievePanel.cs
> +        m_wakgamesAchieve = FindObjectOfType<WakgamesAchieve>();
WakgamesAchieve 컴포넌트가 붙은 오브젝트에 Wakgames 컴포넌트가 없다면 GetComponent 활용은 어려워 보입니다. null 예외 처리를 해두겠습니다.

2024-07-10 07:03 UTC, turtle85917 commented on Assets/Scripts/MenuBehaviour.cs
> +    private RawImage[] RawImage;
아, 이미지 다운로드 테스트용으로 사용해두었습니다. 업적 이미지가 불러와지면 외부에서 받은 RawImage 컴포넌트에 넘겨 확인하는 용이였습니다. `AppendAchievementMessage`에 있는 관련된 코드랑 18번째 줄은 지울까요?

2024-07-11 02:23 UTC, NeuroWhAI commented on Assets/Scripts/AchievePanel.cs
> +        m_wakgamesAchieve = FindObjectOfType<WakgamesAchieve>();
Wakgames와 WakgamesAchieve는 같은 Object의 컴포넌트라고 가정한다면 말이죠. 사실 굳이 다른 오브젝트에 배치할 필요가 없기도 하고... 음 이건 실제 겜 개발자분들이 뭐가 더 편하실지 몰루겠네요. 저라면 한 오브젝트에 왁겜즈 관련 컴포넌트 모아두고 싶을 것 같긴 한데.. 이건 그냥 맘대로 해주세여.

2024-07-11 02:24 UTC, NeuroWhAI commented on Assets/Scripts/MenuBehaviour.cs
> +    private RawImage[] RawImage;
넵 헷갈릴 거 같습니당.

2024-07-13 02:16 UTC, turtle85917 commented on Assets/Scripts/AchievePanel.cs
> +        m_wakgamesAchieve = FindObjectOfType<WakgamesAchieve>();
GetComponent를 호출하여 해당 오브젝트에 있을 경우를 고려하였습니다.

2024-07-16 06:10 UTC, NeuroWhAI approved these changes
병합해도 될 거 같습니다. 👍 

그리고 이제 이걸 기반으로 SDK 릴리즈를 해야하는데 기존엔 cs 파일만 있었는지라 간단하게 했지만 이제 이미지 같은 다른 에셋들도 같이 배포해야하지 않나 싶은데요.
수정하신 분이 가장 잘 아실테니 일단 꼭 필요한 파일들만 SDK 압축 파일에 포함하여 한번 만들어서 디코에 공유 부탁드립니다.
예를 들면 기존 배포된 것들 보시면 MenuScene.cs 이런 건 안 들어가있고 Wakgames.cs 이런 필수 파일만 들어가있습니다.

2024-07-17 10:09 UTC, turtle85917 commented
확인했습니다. SDK로 압축하여 디코에 공유 드리겠습니다.

2024-07-20 12:39 UTC, merged